# About Quiz 3 ...

In [45]:
import numpy as np

Let's make our translation matrix (here u add column of 1s, also in rotation do this, in scaling u do not need to add leading column of 1s)

In [46]:
translate = np.array([[1, 0, -10], [0, 1, 25], [0, 0, 1]]) #last row and colun with 0,0,1 added to match dimesnisons
print(translate)

[[  1   0 -10]
 [  0   1  25]
 [  0   0   1]]


Let's make our scale matrix

In [47]:
scale = np.array([[2, 0, 0], [0, .5, 0], [0, 0, 1]])
print(scale)

[[2.  0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  1. ]]


What happens when we multiply them in this order?

In [48]:
translate@scale #row are transllate @scale is column 

array([[  2. ,   0. , -10. ],
       [  0. ,   0.5,  25. ],
       [  0. ,   0. ,   1. ]])

What happens when we multiply them in this order?

In [49]:
scale@translate

array([[  2. ,   0. , -20. ],
       [  0. ,   0.5,  12.5],
       [  0. ,   0. ,   1. ]])

Alright, let's make some data

In [50]:
data = np.array([[10, 4, 1], [20, 2, 1]])
print(data)

[[10  4  1]
 [20  2  1]]


If I translate my data...

In [51]:
(translate@data.T).T #x minus 10, y plus 25

array([[ 0, 29,  1],
       [10, 27,  1]])

If I scale my data...

In [52]:
(scale@data.T).T #x times 2 y times .5

array([[20.,  2.,  1.],
       [40.,  1.,  1.]])

If I translate then scale then transform my data...

In [53]:
((translate@scale)@data.T).T

array([[10., 27.,  1.],
       [30., 26.,  1.]])

If I scale then translate then transform my data...

want to do this becaise want x  to be at 0

In [54]:
print(data)
((scale@translate)@data.T).T

[[10  4  1]
 [20  2  1]]


array([[ 0. , 14.5,  1. ],
       [20. , 13.5,  1. ]])

In [55]:
(scale@translate@data.T).T

array([[ 0. , 14.5,  1. ],
       [20. , 13.5,  1. ]])

So matrix multiplication is **associative** but not **commutative**:
* (A@B)@C = A@(B@C) but
* A@B != B@A

translation through sclaing or pass sclaing dataing through translation

Which order do you think is a better interpretation of the question in the quiz?

Take home message: **know the order in which you want your transformations done**.

# About Homework 3

Generally, people seem to know how to set up a transformation matrix:
* translation
* scaling
* rotation in 2D
* rotation in 3D
* max-min normalization

The problem seems to come in actually doing the matrix multiply.

Here's a mnemonic that may help you: Pirates say Argh over the Seas (R over C, rows over columns).

Here's a nice little refresher: https://www.mathsisfun.com/algebra/matrix-multiplying.html.

And here we implement matrix multiply using for loops.

In [56]:
def matrix_multiply_slowly(m1, m2):
    if m1.shape[1] != m2.shape[0]:
        print("Can't multiply a ", m1.shape, " matrix by a ", m2.shape, " matrix.")
        return None
    res = []
    # rows
    for rowIndex in range(m1.shape[0]):
        # over
        res.append([]) #add every row , each row gets a new list( maes sense)
        # columns
        for colIndex in range(m2.shape[1]): #for every columns  #add to evry list in res the dot product
            res[-1].append(dot_product_slowly(rowIndex, colIndex, m1[rowIndex], m2[:,colIndex]))
    return np.array(res)

def dot_product_slowly(i, j, v1, v2):
    if len(v1) != len(v2): #if # columns does ot equal noumber of rows 
        print("Can't multiply a vector of length ", len(v1), " with a vector of length ", len(v2), ".")
        return 0
    pairs = list(zip(v1, v2))
    print(pairs)
    print(i, ' ', j, '\t', ' + '.join(['%s*%s'%(i, j) for i, j in pairs]), '\t', np.sum([i*j for i, j in pairs]))
    # print row index, column index and v1 * plus v2 and then sume 
    # tab v1 *v2 
    # sum up the pairwise products
    return np.sum([i*j for i, j in pairs])


done in c this code, so fastserr

In [57]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[2,0],[0,3]])
print(m1,"\n",m2)
print(m1@m2)

[[1 2]
 [3 4]] 
 [[2 0]
 [0 3]]
[[ 2  6]
 [ 6 12]]


In [58]:
print(matrix_multiply_slowly(m1, m2))

[(1, 2), (2, 0)]
0   0 	 1*2 + 2*0 	 2
[(1, 0), (2, 3)]
0   1 	 1*0 + 2*3 	 6
[(3, 2), (4, 0)]
1   0 	 3*2 + 4*0 	 6
[(3, 0), (4, 3)]
1   1 	 3*0 + 4*3 	 12
[[ 2  6]
 [ 6 12]]


### Translate [[1 2 1] [3 7 3] [4 5 4]] to the origin along the y and z dimensions.

In [59]:
data = np.array([[1,2,1],[3,7,3],[4,5,4]])

# add trailing 1s for translation
# there is NO NEED to add a bottom row to make the matrix square
homogenizedData = np.append(data, np.array([np.ones(data.shape[0], dtype=int)]).T, axis=1)

# transformation matrix
transform = np.array([[1,0,0,0],[0,1,0,-np.min(data[:,1])],[0,0,1,-np.min(data[:,2])],[0,0,0,1]]) #last matrix for homogeous cooridnate 
print(homogenizedData)
print(transform)

[[1 2 1 1]
 [3 7 3 1]
 [4 5 4 1]]
[[ 1  0  0  0]
 [ 0  1  0 -2]
 [ 0  0  1 -1]
 [ 0  0  0  1]]


In [60]:
print(matrix_multiply_slowly(transform, homogenizedData.T).T) #lowest value in 2nd and 3rd column of x and y is 0 translated back to orgin!

[(1, 1), (0, 2), (0, 1), (0, 1)]
0   0 	 1*1 + 0*2 + 0*1 + 0*1 	 1
[(1, 3), (0, 7), (0, 3), (0, 1)]
0   1 	 1*3 + 0*7 + 0*3 + 0*1 	 3
[(1, 4), (0, 5), (0, 4), (0, 1)]
0   2 	 1*4 + 0*5 + 0*4 + 0*1 	 4
[(0, 1), (1, 2), (0, 1), (-2, 1)]
1   0 	 0*1 + 1*2 + 0*1 + -2*1 	 0
[(0, 3), (1, 7), (0, 3), (-2, 1)]
1   1 	 0*3 + 1*7 + 0*3 + -2*1 	 5
[(0, 4), (1, 5), (0, 4), (-2, 1)]
1   2 	 0*4 + 1*5 + 0*4 + -2*1 	 3
[(0, 1), (0, 2), (1, 1), (-1, 1)]
2   0 	 0*1 + 0*2 + 1*1 + -1*1 	 0
[(0, 3), (0, 7), (1, 3), (-1, 1)]
2   1 	 0*3 + 0*7 + 1*3 + -1*1 	 2
[(0, 4), (0, 5), (1, 4), (-1, 1)]
2   2 	 0*4 + 0*5 + 1*4 + -1*1 	 3
[(0, 1), (0, 2), (0, 1), (1, 1)]
3   0 	 0*1 + 0*2 + 0*1 + 1*1 	 1
[(0, 3), (0, 7), (0, 3), (1, 1)]
3   1 	 0*3 + 0*7 + 0*3 + 1*1 	 1
[(0, 4), (0, 5), (0, 4), (1, 1)]
3   2 	 0*4 + 0*5 + 0*4 + 1*1 	 1
[[1 0 0 1]
 [3 5 2 1]
 [4 3 3 1]]


### Scale [[1 2 1] [3 7 3] [4 5 4]] by 2 along the x dimension and .5 along the y dimension.

In [61]:
# we are only scaling so we don't NEED to add the homogenous coordinate; but if you did I gave you credit
transform = np.array([[2,0,0],[0,.5,0],[0,0,1]])
print(transform)

[[2.  0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  1. ]]


In [62]:
print(matrix_multiply_slowly(transform, data.T).T)

[(2.0, 1), (0.0, 2), (0.0, 1)]
0   0 	 2.0*1 + 0.0*2 + 0.0*1 	 2.0
[(2.0, 3), (0.0, 7), (0.0, 3)]
0   1 	 2.0*3 + 0.0*7 + 0.0*3 	 6.0
[(2.0, 4), (0.0, 5), (0.0, 4)]
0   2 	 2.0*4 + 0.0*5 + 0.0*4 	 8.0
[(0.0, 1), (0.5, 2), (0.0, 1)]
1   0 	 0.0*1 + 0.5*2 + 0.0*1 	 1.0
[(0.0, 3), (0.5, 7), (0.0, 3)]
1   1 	 0.0*3 + 0.5*7 + 0.0*3 	 3.5
[(0.0, 4), (0.5, 5), (0.0, 4)]
1   2 	 0.0*4 + 0.5*5 + 0.0*4 	 2.5
[(0.0, 1), (0.0, 2), (1.0, 1)]
2   0 	 0.0*1 + 0.0*2 + 1.0*1 	 1.0
[(0.0, 3), (0.0, 7), (1.0, 3)]
2   1 	 0.0*3 + 0.0*7 + 1.0*3 	 3.0
[(0.0, 4), (0.0, 5), (1.0, 4)]
2   2 	 0.0*4 + 0.0*5 + 1.0*4 	 4.0
[[2.  1.  1. ]
 [6.  3.5 3. ]
 [8.  2.5 4. ]]


homogebous cooridnate only for treanslation

### Perform a local max-min normalization of [[1 2 1] [3 7 3] [4 5 4]].
**put everything between 0 and 1**

In [63]:
# transformation matrix
scale = np.array([[1/(max(data[:,0])-min(data[:,0])),0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
translate = np
print(rotate)
print(translate)
# remember what we just learned: order matters! we want to scale the effect of the translation, so we pass the scaling through the translation
# also notice if you do it the other way around we do not get a matrix where every value is between 0 and 1
transform = scale@translate
print(transform)

NameError: name 'rotate' is not defined

In [ ]:
# max-min means translation AND scaling, so we need that trailing column of ones
print(matrix_multiply_slowly(transform, homogenizedData.T).T)

0   0 	 0.3333333333333333*1 + 0.0*2 + 0.0*1 + -0.3333333333333333*1 	 0.0
0   1 	 0.3333333333333333*3 + 0.0*7 + 0.0*3 + -0.3333333333333333*1 	 0.6666666666666667
0   2 	 0.3333333333333333*4 + 0.0*5 + 0.0*4 + -0.3333333333333333*1 	 1.0
1   0 	 0.0*1 + 0.2*2 + 0.0*1 + -0.4*1 	 0.0
1   1 	 0.0*3 + 0.2*7 + 0.0*3 + -0.4*1 	 1.0
1   2 	 0.0*4 + 0.2*5 + 0.0*4 + -0.4*1 	 0.6
2   0 	 0.0*1 + 0.0*2 + 0.3333333333333333*1 + -0.3333333333333333*1 	 0.0
2   1 	 0.0*3 + 0.0*7 + 0.3333333333333333*3 + -0.3333333333333333*1 	 0.6666666666666667
2   2 	 0.0*4 + 0.0*5 + 0.3333333333333333*4 + -0.3333333333333333*1 	 1.0
3   0 	 0.0*1 + 0.0*2 + 0.0*1 + 1.0*1 	 1.0
3   1 	 0.0*3 + 0.0*7 + 0.0*3 + 1.0*1 	 1.0
3   2 	 0.0*4 + 0.0*5 + 0.0*4 + 1.0*1 	 1.0
[[0.         0.         0.         1.        ]
 [0.66666667 1.         0.66666667 1.        ]
 [1.         0.6        1.         1.        ]]


### Rotate [[1 2 1] [3 7 3] [4 5 4]] by 90 degrees around the x dimension.

In [ ]:

# transformation matrix
transform = ??
print(transform.astype(int))

In [ ]:
print(matrix_multiply_slowly(transform, data.T).T)

### Rotate [[1 2 1] [3 7 3] [4 5 4]] by 90 degrees around the y dimension, and center it on zero.

In [ ]:
# transformation matrix, with extra dimension b/c also translating
rotate = ??
translate = ??
print(rotate.astype(int))
print(translate)
# remember what we just learned: order matters! we want to translate the effect of the rotation, so we pass the translation through the rotation
transform = (translate@rotate)
print(transform)

In [ ]:
print(matrix_multiply_slowly(transform, homogenizedData.T).T)

Flwoing data for data visualization

z score puts eveyrhting centered on 0 and standard devaitions from the mean


subtract the mean and divide by standard deviation