# Show me more numpy!

## Review!

How do I see the number of dimensions and number of elements in a numpy array?


In [29]:
# import numpy
import numpy as np
nparray = np.array([[0,1,2,3], [10,11,12,13], [20,21,22,23]])
print("nparray\n", nparray)

# number of dimensions
print(nparray.ndim)

# number of elements
print(nparray.size)
# overall shape
print(nparray.shape)


nparray
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
12
(3, 4)


## Getting into numpy arrays

Indexing into vectors

In [ ]:
v = np.array([1, 2, 3])

# what if i want the second item in v
print(v[1])

Indexing into matrices

In [28]:
m = np.array([[1,2,3], [4,5,6]])
print(m)

#  what if I want the first row second column item in m
print(m[0][1])

[[1 2 3]
 [4 5 6]]
2


In [30]:
# what happens if I do this?
print(m[1]) 

[4 5 6]


In [27]:
# what happens if I do this?
print(m[:, 1])

[2 5]


* these are *slices* of arrays
* a slice of a matrix is a vector
* a slice of a tensor is a matrix or another tensor

Indexing into tensors

In [31]:
t = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]],  [[17,18,19,20], [21,22,23,24]]])

# let's remind ourselves what t looks like
print(t)
print(t.ndim)
print(t.shape)   #3 dimesnions arrays with 2 arrays each with 4 columns 

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
3
(3, 2, 4)


In [35]:
# what if I want the first array 2nd row 3rd column item in t?
print(t[0][1][2])

7


In [36]:
# what is the slice of t indexed like this?
print(t[1])

[[ 9 10 11 12]
 [13 14 15 16]]


In [37]:
# what about like this?
print(t[:,1])

[[ 5  6  7  8]
 [13 14 15 16]
 [21 22 23 24]]


In [38]:
# what about like this?
print(t[:,:,1])

[[ 2  6]
 [10 14]
 [18 22]]


Now you do it!

In [46]:
nparray = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23], [30, 31, 32, 33]])
print("nparray\n", nparray)
print(nparray.ndim)
print(nparray.size)
print(nparray.shape)

nparray
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]
2
16
(4, 4)


In [42]:
# (review!) how do I access the element in the top left corner of nparray?
print(nparray[0][0])

0


In [ ]:
# is there a prettier way?
print(nparray[0, 0])

# this is only marginally prettier for a 2-d array but imagine a 10-d array!
print(nparray[])

In [43]:
# how do I access the whole first column?
print(nparray[:,0])

[ 0 10 20 30]


In [44]:
# what about the whole second row?
print(nparray[1])

[10 11 12 13]


In [50]:

# what about the last two rows?
print(nparray[-2:, :])
print("\n")
print(nparray[2:, :]) #this also works



[[20 21 22 23]
 [30 31 32 33]]


[[20 21 22 23]
 [30 31 32 33]]


In [51]:
# what about the first row and last two columns?
print("first row, last two columns")
print(nparray[0, -2:])   #start from row 0, print last 2 columns till end. can also do [x:y][start:end]

first row, last two columns
[2 3]


In [52]:
# how do I access the 1st and 3rd columns?
print("first and third columns")
print(nparray[:, [0, 2]])

first and third columns
[[ 0  2]
 [10 12]
 [20 22]
 [30 32]]


In [84]:
# let's do it another way
import numpy as np
nparray=np.array([[1,2,3],[4,4,3]])
print(nparray)
print(nparray.shape)
nparray[:,:]=1
print(nparray)
print(nparray.ndim)

# print(nparray[np.ix_(np.arange(nparray.shape[0]), [0, 2])])   #ix is index, arange is rsnge

# what is np.ix_??  
#vector is 1 dimesnional, matrix has 2 elements, tensor has at least 3


[[1 2 3]
 [4 4 3]]
(2, 3)
[[1 1 1]
 [1 1 1]]
2


In [63]:
tesnor=np.array([[[[[1],[2]]]]]) #1 matrix 2 row 1 column
print(tesnor.shape)  #numbr of elements in tuple returned always = ndim
print(tesnor.ndim)  #3 dimesnions (matrix, row, column). 3 []
print(tesnor)


(1, 1, 1, 2, 1)
5
[[[[[1]
    [2]]]]]


## Modifying (slices of) arrays

Modyfying arrays

In [78]:
# how do I *change* the element at 1, 1 of the array?
nparray[1,1] = 101   #changes in place
print(nparray)

[[  1   1   1]
 [  1 101   1]]


In [79]:
# and now for some magic! how do I assign the second row to 1s?
nparray[1] = 1
print(nparray)   #get 4 1's, broadcast, does to everything 
print(nparray.dtype)

[[1 1 1]
 [1 1 1]]
int64


In [82]:
# how do I assign the second row to increasing ints?
print(nparray.shape[0])
nparray[1] = np.arange(nparray.shape[1])   #second row becomes 0 1 2 .  #arange 2,3. nparray[secondrow]=np 3
print(nparray)
print(nparray.dtype)


2
[[1 1 1]
 [0 1 2]]
int64


In [85]:
# how do I assign the second row to 3* itself?
nparray[1] *3
print(nparray)


[[1 1 1]
 [1 1 1]]


In [122]:
import numpy as np
data = np.array([[[2.1, 3.2, 4.3, 5.4, 6.5, 7.6], [7.8, 6.7, 5.6, 4.5, 3.4, 2.3]]])
#print(data)
data=data.astype(int)
#print(data)
data=data*3
#print(data)

# print(data.size)
# print(data.shape)
# print(data.ndim)

data=data.reshape((3,4))
# print(data)

# data=data.tolist()
# print(data)

# print(data[1][2])

# print(data[:,2])

data[:][1]=data[:][1]+4
# print(data)

# print("here","\n")

print(data)

print(data[0,:])
print(data[0,:].min())
data[0,:] =data[0,:]-data[0,:].min()
print(data)


[[ 6  9 12 15]
 [22 25 25 22]
 [15 12  9  6]]
[ 6  9 12 15]
6
[[ 0  3  6  9]
 [22 25 25 22]
 [15 12  9  6]]


Bad pipe message: %s [b'\xd7/\x88P*t\xb4\x99\x9a\xb3^|-)\x83S7\x10  \xfaL\x9b7A\xf9:C\xff5\xa2\xce)=\x92\x01\xae\xff\xf8\x1bW\x08[\x84\xd4\x19\x019\xb1|\xc2\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03']
Bad pipe message: %s [b'\x06\x03\x08\x07', b'\x08\t\x08\n\x08\x0b\x08']
Bad pipe message: %s [b'\x05\x08\x06']
Bad pipe message: %s [b'\x05\x01\x06', b'']
Bad pipe message: %s [b'\x03\x02\x03\x04\x00-\x00\x02\x01\x01\x003\x00&\x00$\x00\x1d\x00 \x0c89\x043B\x01\x96\xad\xddAT\xeb#\xad1\xf8\x95\xb0\xc3\xe5\x94']
Bad pipe message: %s [b'\xbf\xc7r\xba^\x98\xcc\xcc\xa2\x95\xd1#N\x02\xc4\xd8\xb7\xcd \xd6G\x8c-M\x935r\xd9X+r\xf8Yy\xb9\xd5B"\xd9+\x86\x95_(J\xa8\x13\x8df\x8c%']
Bad pipe message: %s [b"X\x99\xf6A\xcd\xc5\x8c\x15TN\xb7\xd5\x03\xd2\xc3\x7f\xd1\xd4\x00\x00\xa6\xc0,\

In [24]:
arr= np.array([[[1,2,3],[3,2,1]],[[3,5,6],[2,4,5]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[1 2 3]
  [3 2 1]]

 [[3 5 6]
  [2 4 5]]]
(2, 2, 3)
3
